import {
  Box,
  Button,
  Chip,
  Paper,
  Stack,
  Typography,
} from '@mui/material';
import { Download } from '@mui/icons-material';

import type { History } from './types';
import { reportLabel } from './utils';

// Props for the history tab: list of generated reports and download handler.
interface ReportHistoryTabProps {
  history: History[];
  onDownload: (item: History) => void;
}

// Converts a date string into a readable local date/time format.
function formatHistoryDate(value?: string) {
  if (!value) return '—';

  const normalized = value.includes(' ') && !value.includes('T') ? value.replace(' ', 'T') : value;
  const date = new Date(normalized);

  if (Number.isNaN(date.getTime())) {
    return 'Unknown date';
  }

  return date.toLocaleString();
}

// Formats the filter object into readable text for display.
function formatFilters(filters: Record<string, unknown>) {
  if (!Object.keys(filters || {}).length) {
    return 'None';
  }

  return Object.entries(filters)
    .map(([key, value]) => `${key}: ${String(value)}`)
    .join(', ');
}

// Displays the saved report generation history and lets the user download successful reports.
export function ReportHistoryTab({ history, onDownload }: ReportHistoryTabProps) {
  return (
    <Paper variant="outlined" sx={{ p: 2 }}>
      <Typography variant="h6" sx={{ mb: 2 }}>Report history</Typography>

      {history.length === 0 ? (
        <Typography color="text.secondary">No report history available.</Typography>
      ) : (
        <Stack spacing={1.5}>
          {history.map((item) => {
            const reportType = item.report_type ?? item.reportType ?? 'sales';
            const generatedBy = item.generated_by ?? item.generatedBy ?? 0;
            const createdAt = item.created_at ?? item.createdAt ?? '';
            const errorMessage = item.error_message ?? item.errorMessage;
            const status = item.status ?? 'Unknown';
            const isSuccess = status.toLowerCase() === 'success';
            const isFailure = status.toLowerCase() === 'failed';

            return (
              <Paper key={item.id} variant="outlined" sx={{ p: 2 }}>
                <Box sx={{ display: 'flex', justifyContent: 'space-between', gap: 2, flexWrap: 'wrap', alignItems: 'flex-start' }}>
                  <Box sx={{ flex: 1, minWidth: 220 }}>
                    {/* Shows the report type name using a label helper. */}
                    <Typography variant="subtitle1" sx={{ fontWeight: 700 }}>{reportLabel(reportType)}</Typography>
                    <Typography variant="body2" color="text.secondary">
                      Generated by: {generatedBy ? `User #${generatedBy}` : 'Unknown user'}
                    </Typography>
                    <Typography variant="body2" color="text.secondary">
                      Generated: {formatHistoryDate(createdAt)}
                    </Typography>
                  </Box>

                  <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, flexWrap: 'wrap' }}>
                    {/* Shows green for success, red for failure, and default otherwise. */}
                    <Chip
                      label={status}
                      color={isSuccess ? 'success' : isFailure ? 'error' : 'default'}
                      size="small"
                    />

                    {/* Download is enabled only if the report generation was successful. */}
                    <Button
                      size="small"
                      variant="outlined"
                      startIcon={<Download />}
                      onClick={() => onDownload(item)}
                      disabled={!isSuccess}
                    >
                      Download
                    </Button>
                  </Box>
                </Box>

                <Box sx={{ mt: 2, display: 'grid', gap: 1, gridTemplateColumns: { xs: '1fr', md: 'repeat(2, minmax(220px, 1fr))' } }}>
                  <Typography variant="body2"><strong>Applied filters:</strong> {formatFilters(item.filters as Record<string, unknown>)}</Typography>
                  <Typography variant="body2"><strong>Format:</strong> {String(item.format || '—').toUpperCase()}</Typography>
                  <Typography variant="body2"><strong>Status:</strong> {status}</Typography>
                  <Typography variant="body2"><strong>Details:</strong> {errorMessage || (isSuccess ? 'Report generated successfully.' : 'No additional details.')}</Typography>
                </Box>

                {errorMessage && (
                  <Typography variant="body2" color="error.main" sx={{ mt: 1 }}>
                    Failed report generation reason: {errorMessage}
                  </Typography>
                )}
              </Paper>
            );
          })}
        </Stack>
      )}
    </Paper>
  );
}
